spring:
  profiles: prod
server:
    port: 9090
    contextPath: Spring-Boot

spring.datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: root
    password: 1234

conn.pool:
    corePoolSize: 20
    maxPoolSize: 100
    queueCapacity: 200
